import { useEffect, useMemo, useRef, useState } from 'react';
import { CheckCircle2, Download, Eye, FileText, FolderOpen, Loader2, LogIn, Pencil, RefreshCw, Upload, X } from 'lucide-react';
import { functionUrl, supabase } from './supabase';
import { prepareLocalFile, type LocalFrame } from './localImport';

type Question = { number:string; question:string; answer:string };
type Page = { source:string; studentName:string; studentId?:string; resolvedStudentName?:string; resolvedStudentId?:string; rosterUserId?:string; rosterMatchStatus?:string; rosterMatchConfidence?:number; assessmentGroup?:string; assessmentTitle?:string; assessmentKind?:string; questionSetId?:string; questionFingerprint?:string; pageNumber?:number|null; totalPages?:number|null; sequence?:number|null; questions:Question[]; questionSignature?:string; handwritingProfile?:string; imageQuality?:string; needsRescan?:boolean; confidence:number; flags:string[] };
type Assessment = { id:string; title:string; kind:string; pageCount:number; studentCount:number; confidence:number; flags:string[]; questionSetId?:string; questionFingerprint?:string; normalizedQuestions?:string[] };
type Grade = { gradeId?:string; assessmentId?:string; assessmentTitle?:string; assessmentKind?:string; questionSetId?:string; studentName:string; studentId?:string; score:number; maxScore:number; percent:number; confidence:number; feedback:string; flags:string[]; items:{number:string;points:number;maxPoints:number;note:string;correct?:boolean}[]; reviewStatus?:'looks_correct'|'needs_review'|'critical_review'; approvalStatus?:'pending'|'approved'; approvedAt?:string };
type Roster = { classroom?:{id?:string;name?:string;subject_code?:string|null;section_name?:string|null}; syncedAt?:string; students?:{userId:string;fullName:string;username?:string|null;studentNumber?:string|null}[] };
type BatchSummary = { id:string; createdAt:string; status:string; pageCount:number; assessmentCount:number; studentCount:number; flagCount:number; approvedCount:number; reviewCount:number; criticalCount:number; classroomName?:string };

const qcSessionKey='buklod_quickcheck_session_v1';
const getQcSession=()=>localStorage.getItem(qcSessionKey)||'';
const setQcSession=(v:string)=>{ if(v)localStorage.setItem(qcSessionKey,v); else localStorage.removeItem(qcSessionKey); };

async function invoke(slug:string, body:unknown) {
  const { data:{ session } } = await supabase.auth.getSession();
  const headers:Record<string,string>={'Content-Type':'application/json','apikey':import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_RWvrYHzgLMvBousgwn4dTg_QawYzwRS'};
  if(session?.access_token) headers.Authorization=`Bearer ${session.access_token}`;
  const opaque=getQcSession(); if(opaque) headers['x-quickcheck-session']=opaque;
  const r=await fetch(functionUrl(slug),{method:'POST',headers,body:JSON.stringify(body)}); const j=await r.json().catch(()=>({})); if(!r.ok||j?.error) throw new Error(j?.error||`Request failed (${r.status})`); return j;
}

function norm(v?:string|null){return(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function studentIdentity(p:Page){return p.rosterUserId||p.resolvedStudentId||p.studentId||p.resolvedStudentName||p.studentName||'Unidentified'}

export default function App(){
  const fileRef=useRef<HTMLInputElement>(null),folderRef=useRef<HTMLInputElement>(null),rubricRef=useRef<HTMLInputElement>(null);
  const previews=useRef<Record<string,LocalFrame>>({});
  const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[authBusy,setAuthBusy]=useState(false),[connected,setConnected]=useState(false),[accountName,setAccountName]=useState('');
  const [roster,setRoster]=useState<Roster>({}),[frames,setFrames]=useState<LocalFrame[]>([]),[pages,setPages]=useState<Page[]>([]),[assessments,setAssessments]=useState<Assessment[]>([]),[grades,setGrades]=useState<Grade[]>([]),[answerKey,setAnswerKey]=useState<any[]>([]);
  const [rubricText,setRubricText]=useState(''),[rubricSource,setRubricSource]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  const [batchId,setBatchId]=useState(''),[released,setReleased]=useState(false),[batches,setBatches]=useState<BatchSummary[]>([]),[historyOpen,setHistoryOpen]=useState(false);
  const [paperGrade,setPaperGrade]=useState<Grade|null>(null),[editGrade,setEditGrade]=useState<Grade|null>(null),[editScore,setEditScore]=useState(''),[editFeedback,setEditFeedback]=useState('');
  const [inspectAssessment,setInspectAssessment]=useState<Assessment|null>(null);

  useEffect(()=>{folderRef.current?.setAttribute('webkitdirectory',''); const p=new URLSearchParams(location.search); const handoff=p.get('handoff'); if(handoff){p.delete('handoff');history.replaceState({},document.title,location.pathname+(p.toString()?`?${p}`:''));setAuthBusy(true);invoke('quickcheck-handoff-redeem-v2',{code:handoff}).then(j=>{setQcSession(j.quickcheckSession||'');setRoster({classroom:j.classroom,students:j.students||[],syncedAt:j.syncedAt});setConnected(true);setAccountName('BUKLOD Faculty');setMessage(`Connected to ${j.classroom?.name||'BUKLOD Classroom'} · ${j.students?.length||0} active students.`);return loadBatches();}).catch(e=>setMessage(e.message)).finally(()=>setAuthBusy(false));} else {supabase.auth.getSession().then(({data})=>{if(data.session){setConnected(true);setAccountName(data.session.user.email||'Faculty');void loadBatches();}else if(getQcSession()){setConnected(true);setAccountName('BUKLOD Faculty');void loadBatches();}})}},[]);

  const grouped=useMemo(()=>{const m=new Map<string,Page[]>();for(const p of pages){const k=`${p.assessmentGroup||'UNSORTED'}::${studentIdentity(p)}`;m.set(k,[...(m.get(k)||[]),p])}return[...m].map(([key,pp])=>({key,name:pp[0]?.resolvedStudentName||pp[0]?.studentName||'Unidentified',pages:pp}))},[pages]);
  const uniqueStudents=useMemo(()=>new Set(pages.map(studentIdentity).map(norm).filter(Boolean)).size,[pages]);
  const reviewCounts=useMemo(()=>({correct:grades.filter(g=>g.reviewStatus==='looks_correct').length,review:grades.filter(g=>g.reviewStatus==='needs_review').length,critical:grades.filter(g=>g.reviewStatus==='critical_review').length,approved:grades.filter(g=>g.approvalStatus==='approved').length}),[grades]);
  const paperPages=useMemo(()=>{if(!paperGrade)return[];const id=norm(paperGrade.studentId||paperGrade.studentName);return pages.filter(p=>(!paperGrade.assessmentId||p.assessmentGroup===paperGrade.assessmentId)&&norm(p.resolvedStudentId||p.studentId||p.resolvedStudentName||p.studentName)===id).sort((a,b)=>(a.sequence||999)-(b.sequence||999))},[paperGrade,pages]);

  async function login(){setAuthBusy(true);setMessage('');try{const r=await fetch(functionUrl('buklod-auth-login-v2'),{method:'POST',headers:{'Content-Type':'application/json','apikey':import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_RWvrYHzgLMvBousgwn4dTg_QawYzwRS'},body:JSON.stringify({identifier,password})});const j=await r.json();if(!j.ok)throw new Error(j.message||'Login failed.');await supabase.auth.setSession({access_token:j.session.access_token,refresh_token:j.session.refresh_token});setConnected(true);setAccountName(j.account?.full_name||j.account?.username||identifier);setPassword('');setMessage('BUKLOD login connected.');await loadBatches();}catch(e){setMessage(e instanceof Error?e.message:'Login failed.')}finally{setAuthBusy(false)}}
  async function logout(){await supabase.auth.signOut();setQcSession('');setConnected(false);setRoster({});setAccountName('');setBatches([]);clearBatch();}
  async function loadBatches(){try{const j=await invoke('quickcheck-records-v1',{action:'list_batches'});setBatches(j.batches||[])}catch(e){setMessage(e instanceof Error?e.message:'Could not load batches.')}}
  async function loadBatch(id:string){setBusy('Loading saved batch…');try{const j=await invoke('quickcheck-records-v1',{action:'get_batch',batchId:id});setBatchId(j.id);setPages(j.pages||[]);setAssessments(j.assessments||[]);setGrades(j.grades||[]);setAnswerKey(j.answerKey||[]);setRubricText(j.rubricText||'');setRubricSource(j.rubricSource||'');setReleased(j.status==='released');setFrames([]);previews.current={};setHistoryOpen(false);setMessage('Saved Batch Record loaded. Original source-paper previews are intentionally not stored; extracted answers remain available.');}catch(e){setMessage(e instanceof Error?e.message:'Load failed.')}finally{setBusy('')}}
  function clearBatch(){setFrames([]);previews.current={};setPages([]);setAssessments([]);setGrades([]);setAnswerKey([]);setRubricText('');setRubricSource('');setBatchId('');setReleased(false);setMessage('New batch ready.');}

  async function addFiles(list:FileList|null){if(!list?.length)return;setBusy('Preparing local files…');const out:LocalFrame[]=[];const errors:string[]=[];for(const f of Array.from(list)){try{const x=await prepareLocalFile(f);for(const q of x){previews.current[q.name]=q;out.push(q)}}catch(e){errors.push(`${f.name}: ${e instanceof Error?e.message:'failed'}`)}}setFrames(v=>[...v,...out]);setMessage(`${out.length} page/segment(s) prepared locally.${errors.length?` Skipped: ${errors.join(' · ')}`:''}`);setBusy('')}
  async function importRubric(file?:File){if(!file)return;setBusy('Reading rubric locally…');try{const inputs=await prepareLocalFile(file);const j=await invoke('quickcheck-process-v1',{action:'rubric_extract',inputs});setRubricText(j.rubricText||'');setRubricSource(file.name);setGrades([]);setBatchId('');setMessage(`Rubric ON · ${j.title||file.name}`)}catch(e){setMessage(e instanceof Error?e.message:'Rubric import failed.')}finally{setBusy('')}}

  async function processBatch(){if(!frames.length)return setMessage('Select PDF, Word, image files, or a folder first.');setBusy('Extracting papers…');setMessage('');try{const extracted:Page[]=[];for(let i=0;i<frames.length;i+=6){const j=await invoke('quickcheck-process-v1',{action:'analyze',pages:frames.slice(i,i+6)});extracted.push(...(j.pages||[]));setBusy(`Extracted ${Math.min(i+6,frames.length)}/${frames.length}…`)}setPages(extracted);setBusy('Grouping by question-set unity and student identity…');const rec=await invoke('quickcheck-process-v1',{action:'reconcile',pages:extracted,rosterContext:roster});setPages(rec.pages||[]);setAssessments(rec.assessments||[]);setBusy(rubricText?'Applying rubric and grading…':'Building suggested grades…');const gr=await invoke('quickcheck-process-v1',{action:'grade',pages:rec.pages||[],rosterContext:roster,rubricText,rubricSource});setPages(gr.pages||[]);setAssessments(gr.assessments||[]);setGrades(gr.grades||[]);setAnswerKey(gr.answerKey||[]);setBusy('Saving structured Batch Record…');const saved=await invoke('quickcheck-records-v1',{action:'create_batch',pages:gr.pages||[],assessments:gr.assessments||[],grades:gr.grades||[],answerKey:gr.answerKey||[],rubricText,rubricSource,rosterContext:roster});setBatchId(saved.batchId);setGrades(saved.grades||gr.grades||[]);setAssessments(saved.assessments||gr.assessments||[]);await loadBatches();setMessage('Checked and saved. Assessment grouping is based on unity of questions, not titles. Teacher review is required before release.');}catch(e){setMessage(e instanceof Error?e.message:'QuickCheck processing failed.')}finally{setBusy('')}}
  async function approval(action:string,gradeId?:string,confirmCritical=false){if(!batchId)return;try{const j=await invoke('quickcheck-records-v1',{action:'approval',batchId,approvalAction:action,gradeId,confirmCritical});if(j.grades)setGrades(j.grades);setReleased(j.status==='released');await loadBatches();setMessage(action==='release'?'All teacher-approved grades released.':'Approval state saved.');}catch(e){setMessage(e instanceof Error?e.message:'Approval failed.')}}
  async function saveGrade(){if(!editGrade?.gradeId||!batchId)return;const score=Number(editScore);if(!Number.isFinite(score)||score<0||score>editGrade.maxScore)return setMessage(`Score must be 0 to ${editGrade.maxScore}.`);setBusy('Saving teacher grade…');try{const j=await invoke('quickcheck-records-v1',{action:'update_grade',batchId,gradeId:editGrade.gradeId,score,feedback:editFeedback});setGrades(j.grades||[]);setEditGrade(null);setMessage('Teacher-adjusted grade saved and returned to Pending approval.');}catch(e){setMessage(e instanceof Error?e.message:'Grade edit failed.')}finally{setBusy('')}}
  function openEdit(g:Grade){if(released)return setMessage('Released grades are locked.');setEditGrade(g);setEditScore(String(g.score));setEditFeedback(g.feedback||'')}
  function downloadCsv(){if(!released)return;const rows=[['Assessment','Student','Student ID','Score','Max Score','Percent','Review','Approval'],...grades.map(g=>[g.assessmentTitle||g.assessmentId||'',g.studentName,g.studentId||'',g.score,g.maxScore,g.percent,g.reviewStatus||'',g.approvalStatus||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='quickcheck-grades.csv';a.click();URL.revokeObjectURL(u)}

  if(!connected)return <main className="shell"><div className="login card"><div className="eyebrow">BUKLOD QUICKCHECK</div><h1>Faculty Sign In</h1><p>Use your BUKLOD username, mobile, or email. Classroom can also open QuickCheck through secure handoff.</p><input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Username / mobile / email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" onKeyDown={e=>e.key==='Enter'&&void login()}/><button className="primary" disabled={authBusy||!identifier||!password} onClick={()=>void login()}>{authBusy?<Loader2 className="spin"/>:<LogIn/>} SIGN IN</button>{message&&<div className="notice">{message}</div>}</div></main>;

  return <main className="shell"><div className="top"><div><div className="eyebrow">CANONICAL STANDALONE WEB</div><h1>BUKLOD QuickCheck</h1><p>{roster.classroom?.name?`${roster.classroom.name} · ${roster.students?.length||0} roster students`:accountName}</p></div><div className="topActions"><button onClick={()=>setHistoryOpen(true)}>BATCH HISTORY</button><button onClick={clearBatch}>NEW BATCH</button><button onClick={()=>void logout()}>SIGN OUT</button></div></div>

  <section className="card"><h2>1. Local-first Import</h2><p>PDF, Word .docx, pictures, or a selected folder. Originals stay local; only temporary prepared content goes to AI, and permanent storage keeps structured results.</p><input ref={fileRef} hidden type="file" multiple accept="image/*,.pdf,.docx" onChange={e=>{void addFiles(e.currentTarget.files);e.currentTarget.value=''}}/><input ref={folderRef} hidden type="file" multiple accept="image/*,.pdf,.docx" onChange={e=>{void addFiles(e.currentTarget.files);e.currentTarget.value=''}}/><div className="buttonRow"><button className="primary" onClick={()=>fileRef.current?.click()}><Upload/> SELECT FILES</button><button onClick={()=>folderRef.current?.click()}><FolderOpen/> SELECT FOLDER</button><span className="pill">{frames.length} prepared page/segment(s)</span></div></section>

  <section className="card"><h2>2. Optional Teacher Rubric</h2><input ref={rubricRef} hidden type="file" accept="image/*,.pdf,.docx" onChange={e=>{void importRubric(e.currentTarget.files?.[0]);e.currentTarget.value=''}}/><div className="split"><textarea value={rubricText} onChange={e=>{setRubricText(e.target.value);setRubricSource(e.target.value?'Pasted / edited rubric':'');setGrades([]);setBatchId('')}} placeholder="Paste rubric criteria here…"/><div className="stack"><button onClick={()=>rubricRef.current?.click()}><FileText/> SELECT RUBRIC FILE</button><button disabled={!rubricText} onClick={()=>{setRubricText('');setRubricSource('')}}>CLEAR RUBRIC</button><span className={`pill ${rubricText?'ok':''}`}>{rubricText?`RUBRIC ON · ${rubricSource}`:'RUBRIC OFF'}</span></div></div></section>

  <section className="card"><button className="primary big" disabled={!!busy||!frames.length} onClick={()=>void processBatch()}>{busy?<Loader2 className="spin"/>:<RefreshCw/>}{busy||'AUTO-SORT BY QUESTION SET & SUGGEST GRADES'}</button>{message&&<div className="notice">{message}</div>}</section>

  {pages.length>0&&<section className="card"><div className="summary"><div><b>{pages.length}</b><span>PROCESSED PAGES</span></div><div><b>{assessments.length}</b><span>QUESTION SETS</span></div><div><b>{uniqueStudents}</b><span>UNIQUE STUDENTS</span></div><div><b>{grades.length}</b><span>GRADES</span></div></div><h2>Detected Assessment Breakdown</h2><p className="muted">Canonical grouping is based on unity of questions/instructions/numbering. Titles are display labels only.</p><div className="grid">{assessments.map(a=><button key={a.id} className="record" onClick={()=>setInspectAssessment(a)}><div><b>{a.title}</b><small>{a.kind} · {a.pageCount} page(s) · {a.studentCount} student(s)</small></div><span className="badge">{Math.round(a.confidence*100)}% match</span><small className="link">VIEW QUESTION SET</small></button>)}</div><h2>Sorted Student Records</h2><div className="grid">{grouped.map(g=>{const p=g.pages[0],grade=grades.find(x=>(!x.assessmentId||x.assessmentId===p.assessmentGroup)&&norm(x.studentId||x.studentName)===norm(p.resolvedStudentId||p.studentId||p.resolvedStudentName||p.studentName));return <button key={g.key} className="record" onClick={()=>grade&&setPaperGrade(grade)}><div><b>{g.name}</b><small>{p.assessmentKind||'Assessment'} · {p.assessmentTitle||p.assessmentGroup} · {g.pages.length} page(s) · sequence {g.pages.map(x=>x.sequence||'?').join('→')}</small></div><span className="badge">{Math.round(Math.min(...g.pages.map(x=>x.confidence))*100)}% match</span><small className="link">{grade?'VIEW PAPER / GRADE':'VIEW RECORD'}</small></button>})}</div></section>}

  {grades.length>0&&<section className="card"><div className="sectionHead"><div><h2>3. Suggested Grades & Teacher Review</h2><p>Click review status or VIEW PAPER to inspect the exact student before approval.</p></div><button disabled={!released} onClick={downloadCsv}><Download/> CSV</button></div><div className="summary"><div><b>{reviewCounts.correct}</b><span>LOOKS CORRECT</span></div><div><b>{reviewCounts.review}</b><span>NEEDS REVIEW</span></div><div><b>{reviewCounts.critical}</b><span>CRITICAL REVIEW</span></div><div><b>{reviewCounts.approved}/{grades.length}</b><span>APPROVED</span></div></div><div className="buttonRow"><button className="primary" onClick={()=>void approval('approve_correct')}>APPROVE ALL CORRECT</button><button onClick={()=>{const c=grades.filter(g=>g.approvalStatus!=='approved'&&g.reviewStatus==='critical_review').length;if(!c||confirm(`${c} critical grade(s) remain. Approve only after personal review?`))void approval('approve_remaining',undefined,c>0)}}>APPROVE REMAINING</button><button className="release" disabled={grades.some(g=>g.approvalStatus!=='approved')||released} onClick={()=>void approval('release')}>{released?'✓ RELEASED':'RELEASE ALL GRADES'}</button></div><div className="tableWrap"><table><thead><tr><th>Assessment</th><th>Student</th><th>Suggested</th><th>Confidence</th><th>Review</th><th>Approval</th><th>Actions</th></tr></thead><tbody>{grades.map(g=><tr key={g.gradeId||`${g.assessmentId}-${g.studentName}`}><td>{g.assessmentTitle||g.assessmentId}</td><td><b>{g.studentName}</b><small>{g.studentId||''}</small></td><td><b>{g.score}/{g.maxScore}</b> ({g.percent}%)</td><td>{Math.round(g.confidence*100)}%</td><td><button className={`status ${g.reviewStatus}`} onClick={()=>setPaperGrade(g)}>{g.reviewStatus?.replace(/_/g,' ').toUpperCase()}</button></td><td>{g.approvalStatus==='approved'?'✓ Approved':'Pending'}</td><td><div className="buttonRow compact"><button onClick={()=>setPaperGrade(g)}><Eye/> VIEW PAPER</button><button disabled={released} onClick={()=>openEdit(g)}><Pencil/> EDIT GRADE</button>{g.approvalStatus!=='approved'&&<button onClick={()=>void approval('approve_grade',g.gradeId)}>APPROVE</button>}</div></td></tr>)}</tbody></table></div></section>}

  {historyOpen&&<Modal title="Batch History" onClose={()=>setHistoryOpen(false)}><button className="refresh" onClick={()=>void loadBatches()}><RefreshCw/> REFRESH</button><div className="stack">{batches.map(b=><button key={b.id} className="history" onClick={()=>void loadBatch(b.id)}><b>{new Date(b.createdAt).toLocaleString()}</b><span>{b.pageCount} pages · {b.assessmentCount} question sets · {b.studentCount} students · {b.status}</span></button>)}</div></Modal>}
  {inspectAssessment&&<Modal title={inspectAssessment.title} onClose={()=>setInspectAssessment(null)}><div className="notice"><b>Question-set identity:</b> grouping ignores title differences. Pages belong together when normalized questions/instructions/numbering are the same or strongly overlapping.</div><p>{inspectAssessment.pageCount} page(s) · {inspectAssessment.studentCount} student(s) · {Math.round(inspectAssessment.confidence*100)}% confidence</p>{inspectAssessment.normalizedQuestions?.length?<ol>{inspectAssessment.normalizedQuestions.map(q=><li key={q}>{q}</li>)}</ol>:<p>No normalized question list stored in this loaded version.</p>}</Modal>}
  {paperGrade&&<Modal wide title={`Paper Review · ${paperGrade.studentName}`} onClose={()=>setPaperGrade(null)}><div className="paperLayout"><div className="stack">{paperPages.length?paperPages.map((p,i)=>{const v=previews.current[p.source];return <div className="paper" key={`${p.source}-${i}`}><div className="paperHead"><b>Page {p.sequence||p.pageNumber||i+1}</b><small>{p.source}</small></div>{v?.dataUrl?<img src={v.dataUrl}/>:v?.text?<pre>{v.text}</pre>:<div className="notice">Original preview is unavailable after refresh/reopen. Extracted answers are shown below.</div>}<div className="questions">{p.questions?.map((q,qi)=><div key={`${q.number}-${qi}`}><b>Q{q.number}</b><small>{q.question}</small><p>Answer: {q.answer||'—'}</p></div>)}</div></div>}):<div className="notice">No matched pages found for this grade.</div>}</div><aside className="gradePanel"><span className={`status ${paperGrade.reviewStatus}`}>{paperGrade.reviewStatus?.replace(/_/g,' ').toUpperCase()}</span><h2>{paperGrade.score}/{paperGrade.maxScore} ({paperGrade.percent}%)</h2><p>{paperGrade.feedback}</p>{paperGrade.flags?.length>0&&<div className="notice">⚑ {paperGrade.flags.join(' · ')}</div>}<div className="stack">{paperGrade.items?.map((x,i)=><div className="item" key={`${x.number}-${i}`}><b>Item {x.number}: {x.points}/{x.maxPoints}</b><span>{x.note}</span></div>)}</div><button disabled={released} onClick={()=>{setPaperGrade(null);openEdit(paperGrade)}}><Pencil/> EDIT GRADE</button>{paperGrade.approvalStatus!=='approved'&&<button className="primary" onClick={()=>void approval('approve_grade',paperGrade.gradeId)}>APPROVE THIS</button>}</aside></div></Modal>}
  {editGrade&&<Modal title={`Edit Grade · ${editGrade.studentName}`} onClose={()=>setEditGrade(null)}><label>Final teacher score<input type="number" min="0" max={editGrade.maxScore} step="0.25" value={editScore} onChange={e=>setEditScore(e.target.value)}/></label><label>Teacher feedback<textarea value={editFeedback} onChange={e=>setEditFeedback(e.target.value)}/></label><button className="primary big" onClick={()=>void saveGrade()}><CheckCircle2/> SAVE TEACHER GRADE</button><p className="muted">Saving a teacher edit resets this grade to Pending approval.</p></Modal>}
  </main>
}

function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`modal ${wide?'wide':''}`}><div className="modalHead"><h2>{title}</h2><button onClick={onClose}><X/> CLOSE</button></div><div className="modalBody">{children}</div></div></div>}
